'use strict';
const fs = require('fs'); const path = require('path'); const vm = require('vm');
const ROOT = path.resolve(__dirname, '..');
function load(s, rel, name) { const src = fs.readFileSync(path.join(ROOT, rel), 'utf8'); vm.runInContext(src + '\nthis.' + name + '=' + name + ';', s, {filename: rel}); }
function fmt(date,tz,fmt) { const o = fmt==='HH:mm' ? {timeZone:tz,hour12:false,hour:'2-digit',minute:'2-digit'} : {timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit'}; const p = new Intl.DateTimeFormat('en-GB',o).formatToParts(date).reduce((a,x)=>(a[x.type]=x.value,a),{}); return fmt==='HH:mm'?p.hour+':'+p.minute:p.year+'-'+p.month+'-'+p.day; }
const s=vm.createContext({console:console,Intl:Intl}), st={sheets:Object.create(null),calendarEvents:[],lockHeld:false,nowIso:'2026-09-05T10:00:00.000Z'}, settings={work_start:'16:00','Slot Duration (min)':'15'};
s.Session={getScriptTimeZone:()=> 'Asia/Baghdad'}; s.Utilities={formatDate:fmt}; s.PropertiesService={getScriptProperties:()=>({getProperty:()=>null,setProperty:()=>{}})}; s.LockService={getScriptLock:()=>({waitLock:()=>{if(st.lockHeld)throw Error('LOCK_ALREADY_HELD');st.lockHeld=true},releaseLock:()=>{st.lockHeld=false}})};
const sh=n=>{if(!st.sheets[n])st.sheets[n]={headers:[],rows:[]};return st.sheets[n]};
s.GoogleSheets={getAllRows:n=>n==='Settings'?[Object.assign({},settings)]:sh(n).rows.map(r=>Object.assign({},r)),queryRows:(n,p)=>s.GoogleSheets.getAllRows(n).filter(p),getHeaders:n=>sh(n).headers.slice(),findRowByColumn:(n,c,v)=>{const r=sh(n).rows.find(x=>String(x[c])===String(v));return r?Object.assign({},r):null},appendRow:(n,o)=>{const t=sh(n);if(!t.headers.length)t.headers=Object.keys(o);const r={};t.headers.forEach(h=>r[h]=Object.prototype.hasOwnProperty.call(o,h)?o[h]:'');t.rows.push(r);return true},updateRowByColumn:(n,c,v,f)=>{const r=sh(n).rows.find(x=>String(x[c])===String(v));if(!r)return false;Object.keys(f).forEach(k=>r[k]=f[k]);return true}};
s.GoogleCalendar={createEvent:p=>{st.calendarEvents.push(p);return 'EVT_'+st.calendarEvents.length}};
[['Result.js','Result'],['Config.js','Config'],['Clock.js','Clock'],['Utils/ULID.js','ULID'],['Utils/IdGenerator.js','IdGenerator'],['Utils/DateUtils.js','DateUtils'],['Utils/LegacySlotTimeParser.js','LegacySlotTimeParser'],['Utils/PhoneUtils.js','PhoneUtils'],['SettingsRepository.js','SettingsRepository'],['StateMachine.js','StateMachine'],['Domain/Validators.js','Validators'],['Infrastructure/Lock.js','Lock'],['Repositories/SlotRepository.js','SlotRepository'],['Repositories/CalendarRepository.js','CalendarRepository'],['ConversationRepository.js','ConversationRepository'],['LogRepository.js','LogRepository'],['Application/CommandExecutor.js','CommandExecutor'],['BusNumberCalculator.js','BusNumberCalculator'],['Application/BookingService.js','BookingService']].forEach(x=>load(s,x[0],x[1]));
s.Clock.now=()=>new Date(st.nowIso); st.sheets.Availability={headers:['slot_id','date','time','sort_key','status','is_available','patient_name','phone','calendar_event_id','reserved_until','reserved_until_unix'],rows:[{slot_id:'SLT_LIVE_1600',date:new Date('2026-09-05T21:00:00.000Z'),time:new Date('2026-09-06T13:00:00.000Z'),sort_key:'202609061600',status:'RESERVED',is_available:true,patient_name:'مريض تجربة',phone:'9647800003333',calendar_event_id:'',reserved_until:'',reserved_until_unix:String(Date.now()+600000)}]};
st.sheets.Conversations={headers:['conversation_id','phone','state','temp_name','slot_id','updated_at'],rows:[{conversation_id:'CONV_LIVE',phone:'9647800003333',state:'WAITING_CONFIRMATION',temp_name:'مريض تجربة',slot_id:'SLT_LIVE_1600',updated_at:''}]};
const r=s.BookingService.handleIncomingMessage('9647800003333','1'); console.error('DEBUG RESULT',JSON.stringify(r)); console.error('DEBUG SLOT',JSON.stringify(st.sheets.Availability.rows[0])); console.error('DEBUG EVENTS',JSON.stringify(st.calendarEvents)); process.exit(0);
