const assert = require('assert');
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const ROOT = path.resolve(__dirname, '..');
const GLOBALS = {
  'CalendarRsvpConfigRepository.js': 'CalendarRsvpConfigRepository',
  'CalendarRsvpSyncRepository.js': 'CalendarRsvpSyncRepository',
  'CalendarRsvpTrigger.js': 'CalendarRsvpTrigger',
  'CalendarRsvpAttendanceService.js': 'CalendarRsvpAttendanceService',
  'GoogleCalendar.js': 'GoogleCalendar',
  'CalendarRepository.js': 'CalendarRepository'
};
function makeResult(){return{ok(d){return{ok:true,data:d};},fail(c,m,d){return{ok:false,error:{code:c,message:m,data:d}};}};}
function makeHarness(){const props={},calls={list:[],get:[],attendance:[],creates:[]},triggers=[];let listQueue=[],getQueue=[],created=0;const sandbox={Result:makeResult(),PropertiesService:{getScriptProperties(){return{getProperty:k=>Object.prototype.hasOwnProperty.call(props,k)?props[k]:null,deleteProperty:k=>delete props[k],setProperties:v=>Object.keys(v).forEach(k=>props[k]=String(v[k])),setProperty:(k,v)=>props[k]=String(v)}}},Lock:{runExclusive:(k,fn)=>fn()},Session:{getEffectiveUser:()=>({getEmail:()=> 'owner@example.com'})},AttendanceService:{markCompleted:c=>{calls.attendance.push({decision:'completed',context:c});return sandbox.__attendanceResult||sandbox.Result.ok({applied:true,alreadyApplied:false});},markNoShow:c=>{calls.attendance.push({decision:'no_show',context:c});return sandbox.__attendanceResult||sandbox.Result.ok({applied:true,alreadyApplied:false});}},Calendar:{Events:{list:(calendarId,params)=>{calls.list.push({calendarId,params:Object.assign({},params)});if(!listQueue.length)return{items:[],nextSyncToken:'default'};const x=listQueue.shift();if(x instanceof Error)throw x;return x;},get:(calendarId,eventId)=>{calls.get.push({calendarId,eventId});if(!getQueue.length)return null;const x=getQueue.shift();if(x instanceof Error)throw x;return x;}}},ScriptApp:{EventType:{ON_EVENT_UPDATED:'ON_EVENT_UPDATED'},getProjectTriggers:()=>triggers.slice(),newTrigger:h=>({forUserCalendar(id){this.calendarId=id;return this;},onEventUpdated(){this.eventType='ON_EVENT_UPDATED';return this;},create(){created++;triggers.push({getHandlerFunction:()=>h,getEventType:()=> 'ON_EVENT_UPDATED',getTriggerSourceId:()=>this.calendarId});}})},CalendarApp:{getCalendarById:id=>({getId:()=>id,createEvent:(title,start,end,options)=>{const r={id,title,start,end,options,guests:[]};calls.creates.push(r);return{getId:()=> 'event-'+calls.creates.length,addGuest:e=>r.guests.push(e),setTag(){},getTag(){return''}}},getEventById:()=>null,getEvents:()=>[]}),getDefaultCalendar:()=>null},__attendanceResult:null,__props:props,__calls:calls,__setListQueue:q=>{listQueue=q.slice();},__setGetQueue:q=>{getQueue=q.slice();},__triggerCreateCount:()=>created};vm.createContext(sandbox);return sandbox;}
function load(s,p){const source=fs.readFileSync(path.join(ROOT,p),'utf8');const name=GLOBALS[path.basename(p)];const suffix=name?'\nthis.'+name+' = '+name+';':'';vm.runInContext(source+suffix,s,{filename:p});}
function loadRsvp(s){load(s,'Repositories/CalendarRsvpConfigRepository.js');load(s,'Repositories/CalendarRsvpSyncRepository.js');load(s,'Infrastructure/CalendarRsvpTrigger.js');load(s,'Application/CalendarRsvpAttendanceService.js');}
function event(responseStatus,extra){return Object.assign({id:'evt-1',iCalUID:'uid-1',status:'confirmed',attendees:[{email:'Secretary@Example.com ',responseStatus}]},extra||{});}
function configure(s){s.__props.HAMZAWE_CALENDAR_ID='clinic-calendar@example.com';s.__props.ATTENDANCE_SECRETARY_EMAIL='Secretary@Example.com';s.__props.HAMZAWE_RSVP_INITIALIZED='true';s.__props.HAMZAWE_RSVP_ACTIVE='true';s.__props.HAMZAWE_RSVP_RESPONSE_CHECKPOINTS='{}';s.__props.HAMZAWE_RSVP_SYNC_TOKEN='sync-1';}
let passed=0;function test(name,fn){try{fn();passed++;console.log('PASS '+name);}catch(e){console.error('FAIL '+name+'\n'+(e.stack||e));process.exitCode=1;}}
test('config normalizes secretary email and requires explicit calendar',()=>{const s=makeHarness();load(s,'Repositories/CalendarRsvpConfigRepository.js');s.__props.HAMZAWE_CALENDAR_ID='cal-1';s.__props.ATTENDANCE_SECRETARY_EMAIL='  SEC@Example.COM ';const r=s.CalendarRsvpConfigRepository.getRuntimeConfig();assert.strictEqual(r.ok,true);assert.strictEqual(r.data.secretaryEmail,'sec@example.com');});
test('stable sync parameter shape excludes forbidden incremental filters',()=>{const s=makeHarness();load(s,'Repositories/CalendarRsvpSyncRepository.js');s.CalendarRsvpSyncRepository.listPage('cal',null,null);s.CalendarRsvpSyncRepository.listPage('cal','tok','page');assert.strictEqual(s.__calls.list[0].params.showDeleted,true);assert.strictEqual(s.__calls.list[0].params.singleEvents,false);assert.strictEqual('syncToken' in s.__calls.list[0].params,false);assert.strictEqual(s.__calls.list[1].params.syncToken,'tok');assert.strictEqual(s.__calls.list[1].params.pageToken,'page');assert.strictEqual('timeMin' in s.__calls.list[1].params,false);});
test('pagination consumes all pages and final nextSyncToken',()=>{const s=makeHarness();loadRsvp(s);s.__setListQueue([{items:[event('needsAction')],nextPageToken:'p2'},{items:[event('tentative',{id:'evt-2',iCalUID:'uid-2'})],nextSyncToken:'final'}]);const r=s.CalendarRsvpAttendanceService._collectPages('cal','tok');assert.strictEqual(r.ok,true);assert.strictEqual(r.data.items.length,2);assert.strictEqual(r.data.nextSyncToken,'final');});
test('baseline is read-only for existing accepted RSVP',()=>{const s=makeHarness();configure(s);s.__props.HAMZAWE_RSVP_INITIALIZED='false';loadRsvp(s);s.__setListQueue([{items:[event('accepted')],nextSyncToken:'base-2'}]);const r=s.CalendarRsvpAttendanceService.initializeBaseline();assert.strictEqual(r.ok,true);assert.strictEqual(s.__calls.attendance.length,0);assert.strictEqual(s.__props.HAMZAWE_RSVP_SYNC_TOKEN,'base-2');});
test('accepted maps to completed and separates actor from execution principal',()=>{const s=makeHarness();configure(s);loadRsvp(s);s.__setListQueue([{items:[event('accepted')],nextSyncToken:'sync-2'}]);const r=s.CalendarRsvpAttendanceService.syncNow();assert.strictEqual(r.ok,true);assert.strictEqual(s.__calls.attendance[0].decision,'completed');assert.strictEqual(s.__calls.attendance[0].context.operator.operatorId,'secretary@example.com');assert.strictEqual(s.__calls.attendance[0].context.executionPrincipal,'owner@example.com');});
test('declined maps to no-show',()=>{const s=makeHarness();configure(s);loadRsvp(s);s.__setListQueue([{items:[event('declined')],nextSyncToken:'sync-2'}]);assert.strictEqual(s.CalendarRsvpAttendanceService.syncNow().ok,true);assert.strictEqual(s.__calls.attendance[0].decision,'no_show');});
test('needsAction and tentative produce no decision',()=>{['needsAction','tentative'].forEach(st=>{const s=makeHarness();configure(s);loadRsvp(s);s.__setListQueue([{items:[event(st)],nextSyncToken:'sync-2'}]);assert.strictEqual(s.CalendarRsvpAttendanceService.syncNow().ok,true);assert.strictEqual(s.__calls.attendance.length,0);});});
test('same RSVP response is idempotently skipped',()=>{const s=makeHarness();configure(s);loadRsvp(s);s.__setListQueue([{items:[event('accepted')],nextSyncToken:'sync-2'}]);assert.strictEqual(s.CalendarRsvpAttendanceService.syncNow().ok,true);s.__setListQueue([{items:[event('accepted')],nextSyncToken:'sync-3'}]);assert.strictEqual(s.CalendarRsvpAttendanceService.syncNow().ok,true);assert.strictEqual(s.__calls.attendance.length,1);});
test('attendeesOmitted refetches complete event',()=>{const s=makeHarness();configure(s);loadRsvp(s);s.__setListQueue([{items:[event('needsAction',{attendeesOmitted:true})],nextSyncToken:'sync-2'}]);s.__setGetQueue([{id:'evt-1',iCalUID:'uid-1',status:'confirmed',attendees:[{email:'secretary@example.com',responseStatus:'accepted'}]}]);assert.strictEqual(s.CalendarRsvpAttendanceService.syncNow().ok,true);assert.strictEqual(s.__calls.get.length,1);assert.strictEqual(s.__calls.attendance.length,1);});
test('incomplete attendee evidence does not checkpoint or mutate',()=>{const s=makeHarness();configure(s);loadRsvp(s);s.__setListQueue([{items:[event('accepted',{attendeesOmitted:true})],nextSyncToken:'sync-2'}]);s.__setGetQueue([{id:'evt-1',iCalUID:'uid-1',attendeesOmitted:true}]);assert.strictEqual(s.CalendarRsvpAttendanceService.syncNow().ok,true);assert.strictEqual(s.__calls.attendance.length,0);assert.strictEqual(JSON.parse(s.__props.HAMZAWE_RSVP_RESPONSE_CHECKPOINTS)['uid-1'],undefined);});
test('cancelled event never becomes no-show',()=>{const s=makeHarness();configure(s);loadRsvp(s);s.__setListQueue([{items:[event('accepted',{status:'cancelled'})],nextSyncToken:'sync-2'}]);assert.strictEqual(s.CalendarRsvpAttendanceService.syncNow().ok,true);assert.strictEqual(s.__calls.attendance.length,0);});
test('retryable Attendance failure preserves replayability',()=>{const s=makeHarness();configure(s);loadRsvp(s);s.__attendanceResult=s.Result.fail('LOCK_TIMEOUT','busy');s.__setListQueue([{items:[event('accepted')],nextSyncToken:'sync-2'}]);const r=s.CalendarRsvpAttendanceService.syncNow();assert.strictEqual(r.ok,false);assert.strictEqual(s.__props.HAMZAWE_RSVP_SYNC_TOKEN,'sync-1');});
test('410 token invalidity triggers one full resync',()=>{const s=makeHarness();configure(s);loadRsvp(s);s.__setListQueue([new Error('HTTP 410 Gone'),{items:[],nextSyncToken:'recovered'}]);const r=s.CalendarRsvpAttendanceService.syncNow();assert.strictEqual(r.ok,true);assert.strictEqual(r.data.restartedFrom410,true);assert.strictEqual(s.__props.HAMZAWE_RSVP_SYNC_TOKEN,'recovered');assert.strictEqual('syncToken' in s.__calls.list[1].params,false);});
test('trigger install is idempotent and single-calendar',()=>{const s=makeHarness();load(s,'Infrastructure/CalendarRsvpTrigger.js');assert.strictEqual(s.CalendarRsvpTrigger.install('cal-1').data.installed,true);assert.strictEqual(s.CalendarRsvpTrigger.install('cal-1').data.existing,true);assert.strictEqual(s.CalendarRsvpTrigger.install('cal-2').error.code,'RSVP_TRIGGER_WRONG_CALENDAR');assert.strictEqual(s.__triggerCreateCount(),1);});
test('appointment creation uses configured calendar only after activation and adds secretary',()=>{const s=makeHarness();configure(s);load(s,'Infrastructure/GoogleCalendar.js');load(s,'Repositories/CalendarRsvpConfigRepository.js');load(s,'Repositories/CalendarRepository.js');const r=s.CalendarRepository.createAppointmentEvent({title:'A',startTime:new Date(),endTime:new Date()});assert.strictEqual(r.ok,true);assert.strictEqual(s.__calls.creates[0].id,'clinic-calendar@example.com');assert.deepStrictEqual(s.__calls.creates[0].guests,['secretary@example.com']);});
console.log('\n'+passed+' Calendar RSVP hardening tests passed.');
